# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_document_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, null=True)),
                ('time', models.CharField(max_length=800, null=True)),
                ('docfile1', models.FileField(upload_to=upload.models.get_upload_path)),
            ],
        ),
    ]
